
services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "4000:3000"
    volumes:
      - "./backend/:/app"
      - "/app/node_modules"
    depends_on:
      - mongo

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "3000:3000"
    volumes:
      - "./frontend:/app"
      - "/app/node_modules"
    depends_on:
      - api

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: parkit
      MONGO_INITDB_ROOT_PASSWORD: parkit
    volumes:
      - db-data:/data/db
        
  lpr:
    image: gbothmen/parkit-lpr-app:latest
    container_name: lpr
    ports:
      - "5000:5000"
    depends_on:
      - api
      - mongo

  voice-assistant:
    build:
      context: ./voice-assistant
      dockerfile: Dockerfile
    container_name: voice-assistant
    ports:
      - "8000:8000"
    volumes:
      - ./voice-assistant:/app

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    command:
      - "http"
      - "http://host.docker.internal:8000"
    environment:
      NGROK_AUTHTOKEN: 2wj1jvcg3Qjg86Csg4NulJfT3KH_5TZjeMnAiRkyzDUok5Yrh
    ports:
      - 4040:4040

  fastapi:
      build:
        context: ./ia-reclamation
        dockerfile: Dockerfile
      container_name: fastapi
      ports:
        - "8008:8008"
      volumes:
        - ./ia-reclamation:/app
      environment:
        - DOCKER_ENV=true  # Skip GUI in helmi.py
      depends_on:
        - api
        - mongo
      command: ["uvicorn", "model_server:app", "--host", "0.0.0.0", "--port", "8008", "--reload"]

volumes:
  db-data: {}
  