version: "3"
services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "4000:3000"
    volumes:
      - "./backend/:/app"
      - "/app/node_modules"  # Prevents overriding node_modules
    depends_on:
      - mongo

  web:
    build:
      context: ./frontend/parkit-front
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "5173:5173"
    volumes:
      - "./frontend/parkit-front:/app/public"
      - "/app/node_modules"  # Prevents overriding node_modules
    depends_on:
      - api

  backoffice:
    build:
      context: ./frontend/parkit-back  # Path to Back Office React app
      dockerfile: Dockerfile
    container_name: backoffice
    ports:
      - "5174:5174"  # Runs on a different port than Front Office
    volumes:
      - "./frontend/parkit-back/:/src"
      - "/src/node_modules"  # Prevents overriding node_modules
      - "./frontend/parkit-back/public:/src/public"
    depends_on:
      - api

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: parkit
      MONGO_INITDB_ROOT_PASSWORD: parkit
    volumes:
      - db-data:/data/db

volumes:
  db-data: {}
