version: "3"
services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "4000:3000"
    volumes:
      - "./backend/:/app"
      - "/app/node_modules"  # Prevents overriding node_modules

  web:
    build:
      context: ./frontend/parkit-front
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "5173:5173"
    volumes:
      - "./frontend/parkit-front/:/src"
      - "/src/node_modules"  # Prevents overriding node_modules
      - "./frontend/parkit-front/public:/src/public" 

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: parkit
      MONGO_INITDB_ROOT_PASSWORD: parkit
    volumes:
      - db-data:/data/db

volumes:
  db-data: {}
