version: "3"
services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "4000:3000"
    volumes:
      - "./backend/:/app"
      - "/app/node_modules"  # Préserve node_modules
    depends_on:
      - mongo

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "3000:3000"  # Modifier en 3000 pour create-react-app
    volumes:
      - "./frontend:/app"
      - "/app/node_modules"  # Préserver node_modules
    depends_on:
      - api

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: parkit
      MONGO_INITDB_ROOT_PASSWORD: parkit
    volumes:
      - db-data:/data/db

volumes:
  db-data: {}