version: "3"
services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "4000:3000"
    volumes:
      - "./backend/:/app"
      - "/app/node_modules"  # Préserve node_modules
    depends_on:
      - mongo

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "3000:3000"  # Modifier en 3000 pour create-react-app
    volumes:
      - "./frontend:/app"
      - "/app/node_modules"  # Préserver node_modules
    depends_on:
      - api

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: parkit
      MONGO_INITDB_ROOT_PASSWORD: parkit
    volumes:
      - db-data:/data/db
  
  ia-reclamation:
    build:
      context: ./ia-reclamation
      dockerfile: Dockerfile
    container_name: ia-reclamation
    ports:
      - "8000:8000"
    entrypoint: /bin/bash  # Override entrypoint to keep container running
    tty: true
    volumes:
      - ./ia-reclamation:/app
      - ./type:/app/type
    environment:
      - DOCKER_ENV=true
    depends_on:
      - mongo

  
  lpr:
    build:
      context: ./lpr-python
      dockerfile: Dockerfile
    container_name: lpr
    ports:
      - "5000:5000"
    volumes:
      - ./lpr-python:/app
    depends_on:
      - api
      - mongo
volumes:
  db-data: {}
