
services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "4000:3000"
    volumes:
      - "./backend/:/app"
      - "/app/node_modules"
    depends_on:
      - mongo

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "3000:3000"
    volumes:
      - "./frontend:/app"
      - "/app/node_modules"
    depends_on:
      - api

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: parkit
      MONGO_INITDB_ROOT_PASSWORD: parkit
    volumes:
      - db-data:/data/db
  
  ia-reclamation:
    build:
      context: ./ia-reclamation
      dockerfile: Dockerfile
    container_name: ia-reclamation
    ports:
      - "8000:8000"
    entrypoint: /bin/bash  # Override entrypoint to keep container running
    tty: true
    volumes:
      - ./ia-reclamation:/app
      - ./type:/app/type
    environment:
      - DOCKER_ENV=true
    depends_on:
      - mongo

  
  lpr:
    build:
      context: ./lpr-python
      dockerfile: Dockerfile
    container_name: lpr
    ports:
      - "5000:5000"
    volumes:
      - ./lpr-python:/app
    depends_on:
      - api
      - mongo

  voice-assistant:
    build:
      context: ./voice-assistant
      dockerfile: Dockerfile
    container_name: voice-assistant
    ports:
      - "8000:8000"
    volumes:
      - ./voice-assistant:/app

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    command:
      - "http"
      - "http://host.docker.internal:8000"
    environment:
      NGROK_AUTHTOKEN: 2wj1jvcg3Qjg86Csg4NulJfT3KH_5TZjeMnAiRkyzDUok5Yrh
    ports:
      - 4040:4040

volumes:
  db-data: {}
