version: "3"
services:
  api:
    image: ihebmsaed/pidev-twin-backend:latest
    container_name: api
    ports:
      - "4000:3000"
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: parkit
      MONGO_INITDB_ROOT_PASSWORD: parkit
    volumes:
      - db-data:/data/db

volumes:
  db-data: {}
